@startuml ER

/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "開発対象システム" as target_system {
    entity "事業所マスタ(companies)" as companies <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + 事業所ID [PK](company_id)
        --
        事業所名(company_name)
        電話番号(phone)
        郵便番号(zip_code)
        住所(address)
        登録日時(created_at)
        更新日時(updated_at)
        削除日時(deleted_at)
        削除フラグ(is_deleted)
    }

    entity "ユーザーマスタ(users)" as users <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + ユーザID [PK](user_id)
        --
        # 事業所ID [FK](company_id)
        姓(last_name)
        名(firtst_name)
        メールアドレス(email)
        # 権限 [FK](authority_id)
        登録日時(created_at)
        更新日時(updated_at)
        削除日時(deleted_at)
        削除フラグ(is_deleted)
    }

    entity "権限マスタ(authority)" as authority <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + 権限ID [PK](authority_id)
        --
        権限名(authority_name)
        登録日時(created_at)
    }

    entity "Documents" as documents <<M,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + ドキュメントID(document_id) [PK]
        --
        ドキュメント名
        # 事業所ID [FK](company_id)
        ステータス
        タイトル
        クライアント名
        自社名
        契約開始日
        契約終了日
        契約締結日
        更新拒絶期日
        メモ
        ドキュメント
        登録日時(created_at)
        更新日時(updated_at)
    }

    entity "ステータスマスタ" as status <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + ステータスID [PK]
        --
        ステータス名
        登録日時(created_at)
    }
}

companies ||--o{ users
companies ||--o{ documents
users ||--|| authority
documents ||--|| status

@enduml
