@startuml ER

/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "開発対象システム" as target_system {
    entity "事業所マスタ(companies)" as order <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + 事業所ID [PK](company_id)
        --
        事業所名(company_name)
        電話番号(phone)
        郵便番号(zip_code)
        住所(address)
        登録日時(created_at)
        更新日時(updated_at)
        削除日時(deleted_at)
        削除フラグ(is_deleted)
    }

    entity "ユーザーマスタ(users)" as order_detail <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + ユーザID [PK](user_id)
        --
        # 事業所ID [FK](company_id)
        姓(last_name)
        名(firtst_name)
        メールアドレス(email)
        # 権限 [FK](authority_id)
        登録日時(created_at)
        更新日時(updated_at)
        削除日時(deleted_at)
        削除フラグ(is_deleted
    }

    entity "権限マスタ" as sku <<M,MASTER_MARK_COLOR>> {
        + SKU [PK]
        --
        # 商品ID [FK]
        カラー
        サイズ
        重量
        販売単価
        仕入単価
    }

    entity "商品マスタ" as product <<M,MASTER_MARK_COLOR>> {
        + 商品ID [PK]
        --
        商品名
        原産国
        # 仕入先ID [FK]
        商品カテゴリ
        配送必要日数
    }

    entity "仕入先マスタ" as vendor <<M,MASTER_MARK_COLOR>> {
        + 仕入先ID [PK]
        --
        仕入れ先名
        郵便番号
        住所
        電話番号
        FAX番号
    }
}


@enduml
